name: flutter_sensors_plus
description: "All types of sensors event listener plugin for flutter (Android & iOS)."
version: 1.0.1
homepage: https://github.com/rohitsoni9/flutter_sensor_plus.git

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true